(deftheme frank-doom
  "Created 2023-11-25.")

(custom-theme-set-variables
 'frank-doom
 '(evil-want-Y-yank-to-eol nil)
 '(Info-fontify-angle-bracketed-flag nil)
 '(ansi-color-names-vector ["#0a0814" "#f2241f" "#67b11d" "#b1951d" "#4f97d7" "#a31db1" "#28def0" "#b2b2b2"])
 '(debug-on-error nil)
 '(global-evil-vimish-fold-mode t)
 '(imenu-list-position 'left)
 '(imenu-list-size 0.2)
 '(markdown-enable-math t)
 '(markdown-fontify-code-blocks-natively t)
 '(org-adapt-indentation nil)
 '(org-agenda-files '("~/onedrive/code-snippets/emacs.org" "~/onedrive/code-snippets/ml-math.org"))
 '(org-cycle-emulate-tab nil)
 '(org-download-heading-lvl nil)
 '(org-download-image-dir "./error-global-org-download-image-dir")
 '(org-download-method 'directory)
 '(org-edit-src-content-indentation 0)
 '(org-file-apps '(("\\.docx?\\'" . "wps %s") (auto-mode . emacs) (directory . emacs) ("\\.mm\\'" . default) ("\\.x?html?\\'" . default) ("\\.pdf\\'" . default)))
 '(org-image-actual-width nil)
 '(org-list-indent-offset 2)
 '(org-preview-latex-default-process 'dvisvgm)
 '(org-startup-with-inline-images nil)
 '(package-selected-packages '(ahk-mode undo-tree queue spinner org-plus-contrib magit-section compat shrink-path fcitx org-fragtog org-elp web-mode tagedit slim-mode scss-mode sass-mode pug-mode haml-mode emmet-mode org-preview-html company yasnippet cdlatex json-mode dash-functional anaconda-mode pythonic evil-vimish-fold vimish-fold yaml-mode vimrc-mode phi-rectangle rectangle-utils edit-indirect auto-complete-auctex company-auctex auto-completion-auctex auctex doom-modeline ewal-doom-themes doom-acario-dark-theme doom-solarized-dark-theme doom-material-theme doom-dark+-theme doom-theme doom-themes-theme spaceline-all-the-icons all-the-icons org-category-capture alert log4e gntp markdown-mode magit-popup gitignore-mode magit git-commit with-editor transient ivy-posframe packed wgrep smex ivy-hydra counsel-projectile counsel swiper ivy yapfify ws-butler winum which-key volatile-highlights vi-tilde-fringe uuidgen use-package unfill toc-org spaceline smeargle restart-emacs rainbow-delimiters pyvenv pytest pyenv-mode py-isort popwin pip-requirements persp-mode pcre2el paradox orgit org-projectile org-present org-pomodoro org-mime org-download org-bullets open-junk-file neotree mwim move-text mmm-mode markdown-toc magit-gitflow macrostep lorem-ipsum live-py-mode linum-relative link-hint indent-guide imenu-list hy-mode hungry-delete htmlize hl-todo highlight-parentheses highlight-numbers highlight-indentation helm-themes helm-swoop helm-pydoc helm-projectile helm-mode-manager helm-make helm-gitignore helm-flx helm-descbinds helm-company helm-c-yasnippet helm-ag google-translate golden-ratio gnuplot gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link gh-md fuzzy flx-ido fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-ediff evil-args evil-anzu eval-sexp-fu elisp-slime-nav dumb-jump diminish define-word cython-mode company-statistics company-anaconda column-enforce-mode cnfonts clean-aindent-mode auto-yasnippet auto-highlight-symbol auto-compile aggressive-indent adaptive-wrap ace-window ace-link ace-jump-helm-line ac-ispell))
 '(safe-local-variable-values '((org-image-actual-width quote (400)) (org-image-actual-width quote (600)) (eval setq-local org-download-image-dir (concat (file-name-base (buffer-file-name)) ".assets"))))
 '(smtpmail-smtp-server "smtp.qq.com")
 '(smtpmail-smtp-service 25)
 '(yaml-indent-offset 4)
 '(desktop-save-mode nil)
 '(custom-safe-themes '("c517e98fa036a0c21af481aadd2bdd6f44495be3d4ac2ce9d69201fcb2578533" "ab2cbf30ab758c5e936b527377d543ce4927001742f79519b62c45ba9dd9f55e" "3da4d7317a707d720dcc332565510fc5631d3637fe10b046b2373af705b6042b" "6395575116fccbcc921a7134c3da729795fdf018660e56d901514410a5ad9c26" default)))

(custom-theme-set-faces
 'frank-doom
 '(default ((t (:family "Sarasa Fixed SC" :foundry "outline" :slant normal :weight normal :height 120 :width normal))))
 '(evil-search-highlight-persist-highlight-face ((t (:inherit lazy-highlight :background "LightGoldenrod2" :foreground "black"))))
 '(hl-line ((t (:extend t :background "sienna4"))))
 '(hlt-regexp-level-1 ((t (:background "orange"))))
 '(isearch ((t nil)))
 '(markdown-blockquote-face ((t (:inherit font-lock-doc-face))))
 '(markdown-code-face ((t (:inherit fixed-pitch :family "Sarasa Fixed SC"))))
 '(mode-line ((t (:background "#222226" :foreground "#b2b2b2" :box (:line-width 1 :color "#5d4d7a") :height 129 :foundry "yahei" :family "consolas"))))
 '(font-latex-sectioning-0-face ((t (:height 1.0))))
 '(font-latex-sectioning-1-face ((t (:height 1.0))))
 '(font-latex-sectioning-2-face ((t (:height 1.0))))
 '(font-latex-sectioning-3-face ((t (:height 1.0))))
 '(font-latex-sectioning-4-face ((t (:height 1.0))))
 '(font-latex-sectioning-5-face ((t (:height 1.0))))
 '(font-latex-slide-title-face ((t (:height 1.0))))
 '(info-title-1 ((t (:height 1.0))))
 '(info-title-2 ((t (:height 1.0))))
 '(info-title-3 ((t (:height 1.0))))
 '(info-title-4 ((t (:height 1.0))))
 '(markdown-header-face ((t (:height 1.0))))
 '(markdown-header-face-1 ((t (:height 1.0))))
 '(markdown-header-face-2 ((t (:height 1.0))))
 '(markdown-header-face-3 ((t (:height 1.0))))
 '(markdown-header-face-4 ((t (:height 1.0))))
 '(markdown-header-face-5 ((t (:height 1.0))))
 '(markdown-header-face-6 ((t (:height 1.0))))
 '(org-document-title ((t (:height 1.0))))
 '(org-level-1 ((t (:height 1.0))))
 '(org-level-2 ((t (:height 1.0))))
 '(org-level-3 ((t (:height 1.0))))
 '(org-level-4 ((t (:height 1.0))))
 '(org-level-5 ((t (:height 1.0))))
 '(org-level-6 ((t (:height 1.0))))
 '(org-level-7 ((t (:height 1.0))))
 '(org-level-8 ((t (:height 1.0)))))

(provide-theme 'frank-doom)
